export const GET_WEATHER = "GET_WEATHER";
export const WATCH_GET_WEATHER = "WATCH_GET_WEATHER";
export const IS_WEATHER_LOADING = "IS_WEATHER_LOADING";
export const WATCH_IS_WEATHER_LOADING = "WATCH_IS_WEATHER_LOADING";